######################################################################
# Automatically generated by qmake (3.0) ?? ????. 19 14:19:49 2016
######################################################################

TEMPLATE = app
TARGET = Adapter
INCLUDEPATH += .

# Input
SOURCES += main.cpp
