######################################################################
# Automatically generated by qmake (3.0) ?? ????. 19 11:25:49 2016
######################################################################

TEMPLATE = app
TARGET = FactoryMethod2
INCLUDEPATH += .

# Input
SOURCES += main.cpp
